# Generated by Django 3.2.25 on 2025-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0016_alter_logentry_serialized_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['content_type', 'object_id'], name='auditlog_contenttype_objid_idx'),
        ),
    ]

